const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={events:[],weekend:null,day:"All",quick:new Set(),category:"All",area:"All",sort:"curated",roadTrip:false,query:"",favorites:new Set(JSON.parse(localStorage.getItem("ctw.favorites")||"[]")),plan:new Set(JSON.parse(localStorage.getItem("ctw.plan")||"[]"))};
const esc=(value)=>String(value??"").replace(/[&<>'"]/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const maps=(e)=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(e.address)}`;
const persist=()=>{localStorage.setItem("ctw.favorites",JSON.stringify([...state.favorites]));localStorage.setItem("ctw.plan",JSON.stringify([...state.plan]));};
const toast=(message)=>{const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2300)};
const eventById=(id)=>state.events.find((e)=>e.id===id);
const priceSort=(e)=>e.priceValue??9999;
const dateTime=(e)=>{const hit=e.time.match(/(\d{1,2}):(\d{2})\s*(AM|PM)/i);if(!hit)return new Date(`${e.date}T23:59:00`);let h=+hit[1]%12+(hit[3].toUpperCase()==="PM"?12:0);return new Date(`${e.date}T${String(h).padStart(2,"0")}:${hit[2]}:00`)};
function updateEdition(){const w=state.weekend;document.title=`Cincinnati This Weekend · ${w.shortLabel}, ${w.endDate.slice(0,4)}`;$("#weekend-date").textContent=w.label;$("#edition-label").textContent=`THE ${w.shortLabel.toUpperCase()} EDIT`;$("#verified-label").textContent=w.verifiedAt;$("#hero-count").textContent=state.events.length;const today=new Date().toLocaleDateString("en-CA",{timeZone:w.timezone});if(today>w.endDate){const banner=document.createElement("div");banner.className="stale-banner";banner.textContent=`This ${w.shortLabel} edition has ended. The next verified edition is due Wednesday at 9:00 AM Eastern.`;document.body.insertBefore(banner,document.querySelector("main"));}}
function populateSelects(){const add=(select,values)=>values.sort().forEach(v=>select.add(new Option(v,v)));add($("#category-select"),[...new Set(state.events.map(e=>e.category))]);add($("#area-select"),[...new Set(state.events.map(e=>e.neighborhood))]);}
function filtered(){const today=new Date().toLocaleDateString("en-CA",{timeZone:state.weekend.timezone});let list=state.events.filter(e=>state.roadTrip||!e.roadTrip);if(state.day!=="All")list=list.filter(e=>state.day==="Today"?e.date===today:e.day===state.day);if(state.query){const q=state.query.toLowerCase();list=list.filter(e=>[e.title,e.venue,e.neighborhood,e.category,e.description,...e.tags].join(" ").toLowerCase().includes(q));}if(state.category!=="All")list=list.filter(e=>e.category===state.category);if(state.area!=="All")list=list.filter(e=>e.neighborhood===state.area);for(const q of state.quick){if(q==="free")list=list.filter(e=>e.priceValue===0);else if(q==="under25")list=list.filter(e=>e.priceValue!==null&&e.priceValue<=25);else list=list.filter(e=>e.tags.includes(q));}const sorters={curated:(a,b)=>Number(b.featured)-Number(a.featured)||dateTime(a)-dateTime(b),time:(a,b)=>dateTime(a)-dateTime(b),price:(a,b)=>priceSort(a)-priceSort(b),drive:(a,b)=>a.travelMinutes-b.travelMinutes};return list.sort(sorters[state.sort]);}
function featureCard(e,i){return `<article class="feature-card" data-detail="${esc(e.id)}" tabindex="0"><span class="feature-index">EDITOR'S ${String(i+1).padStart(2,"0")} · ${esc(e.day.toUpperCase())}</span><h3>${esc(e.title)}</h3><p>${esc(e.description)}</p><div class="feature-meta">${esc(e.time)} · ${esc(e.neighborhood)}</div></article>`}
function eventCard(e){const saved=state.favorites.has(e.id);return `<article class="event-card ${e.roadTrip?"roadtrip":""}"><div class="card-top"><span class="date-badge">${esc(e.day)} · ${esc(e.category)}${e.roadTrip?" · Worth the drive":""}</span><button class="save-event ${saved?"saved":""}" data-save="${esc(e.id)}" aria-label="${saved?"Remove from":"Save to"} favorites">${saved?"♥":"♡"}</button></div><h3>${esc(e.title)}</h3><p class="description">${esc(e.description)}</p><div class="card-facts"><span><i>◷</i>${esc(e.time)}</span><span><i>⌖</i>${esc(e.venue)} · ${esc(e.neighborhood)}</span><span><i>$</i>${esc(e.priceLabel)}${e.travelMinutes?` · about ${e.travelMinutes} min drive`:""}</span></div><div class="tag-row">${e.tags.slice(0,3).map(t=>`<span class="tag">${esc(t)}</span>`).join("")}</div><div class="card-actions"><button data-detail="${esc(e.id)}">Details</button><button data-plan="${esc(e.id)}">${state.plan.has(e.id)?"In my plan ✓":"Add to plan +"}</button><a href="${esc(e.sourceUrl)}" target="_blank" rel="noreferrer">Source ↗</a></div></article>`}
function render(){const list=filtered();$("#event-grid").innerHTML=list.map(eventCard).join("");$("#empty-state").hidden=!!list.length;$("#result-summary").textContent=`${list.length} of ${state.events.filter(e=>state.roadTrip||!e.roadTrip).length} verified picks shown`;$("#saved-count").textContent=state.favorites.size;$("#plan-count").textContent=state.plan.size;const chips=[];if(state.day!=="All")chips.push(state.day);if(state.query)chips.push(`“${state.query}”`);if(state.category!=="All")chips.push(state.category);if(state.area!=="All")chips.push(state.area);chips.push(...state.quick);if(state.roadTrip)chips.push("Worth the drive on");$("#active-filters").innerHTML=chips.map(c=>`<span class="filter-chip">${esc(c)}</span>`).join("");bindDynamic();renderPlan();}
function bindDynamic(){$$("[data-save]").forEach(b=>b.onclick=()=>toggleSave(b.dataset.save));$$("[data-plan]").forEach(b=>b.onclick=()=>togglePlan(b.dataset.plan));$$("[data-detail]").forEach(b=>{b.onclick=()=>openDetail(b.dataset.detail);b.onkeydown=(x)=>{if(x.key==="Enter")openDetail(b.dataset.detail)}})}
function toggleSave(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);persist();toast(state.favorites.has(id)?"Saved for later":"Removed from saved");render()}
function togglePlan(id){state.plan.has(id)?state.plan.delete(id):state.plan.add(id);persist();toast(state.plan.has(id)?"Added to your weekend":"Removed from your plan");render();if(state.plan.has(id))openDrawer()}
function openDetail(id){const e=eventById(id);if(!e)return;$("#dialog-content").innerHTML=`<div class="dialog-inner"><button class="dialog-close" aria-label="Close">×</button><span class="dialog-kicker">${esc(e.day)} · ${esc(e.category)}${e.roadTrip?" · Worth the drive":""}</span><h2>${esc(e.title)}</h2><p>${esc(e.description)}</p><div class="dialog-details"><b>${esc(e.time)} · ${esc(e.date)}</b><span>${esc(e.venue)} · ${esc(e.address)}</span><span>${esc(e.priceLabel)} · ${esc(e.age)}</span>${e.travelMinutes?`<span>About ${e.travelMinutes} minutes from central Cincinnati</span>`:""}<span>Verified ${esc(e.lastVerified)} from ${esc(e.sourceName)}</span></div><div class="dialog-actions"><a class="primary" href="${esc(e.sourceUrl)}" target="_blank" rel="noreferrer">Source / tickets ↗</a><a href="${maps(e)}" target="_blank" rel="noreferrer">Directions ↗</a><button data-plan-dialog="${esc(e.id)}">${state.plan.has(e.id)?"Remove from plan":"Add to plan"}</button><button data-save-dialog="${esc(e.id)}">${state.favorites.has(e.id)?"Unsave":"Save"}</button></div></div>`;$(".dialog-close").onclick=()=>$("#event-dialog").close();$("[data-plan-dialog]").onclick=()=>{togglePlan(e.id);$("#event-dialog").close()};$("[data-save-dialog]").onclick=()=>{toggleSave(e.id);$("#event-dialog").close()};$("#event-dialog").showModal()}
function renderPlan(){const events=[...state.plan].map(eventById).filter(Boolean).sort((a,b)=>dateTime(a)-dateTime(b));$("#plan-list").innerHTML=events.length?events.map(e=>`<div class="plan-item"><span class="day">${esc(e.day.slice(0,3).toUpperCase())}</span><div><b>${esc(e.title)}</b><small>${esc(e.time)} · ${esc(e.neighborhood)}</small></div><button data-remove-plan="${esc(e.id)}" aria-label="Remove">×</button></div>`).join(""):`<p class="drawer-note">Add events from the guide and they’ll line up here by day and time.</p>`;$$('[data-remove-plan]').forEach(b=>b.onclick=()=>togglePlan(b.dataset.removePlan));const signatures=new Map();let conflict="";for(const e of events){const key=`${e.date}|${dateTime(e).getHours()}`;if(signatures.has(key)){conflict=`Possible overlap: ${signatures.get(key)} and ${e.title} start in the same hour.`;break}signatures.set(key,e.title)}$("#plan-warning").hidden=!conflict;$("#plan-warning").textContent=conflict;}
function openDrawer(){$("#plan-drawer").classList.add("open");$("#plan-drawer").setAttribute("aria-hidden","false");$("#drawer-scrim").hidden=false}
function closeDrawer(){$("#plan-drawer").classList.remove("open");$("#plan-drawer").setAttribute("aria-hidden","true");$("#drawer-scrim").hidden=true}
function reset(){state.day="All";state.quick.clear();state.category="All";state.area="All";state.query="";state.roadTrip=false;$("#search-input").value="";$("#category-select").value="All";$("#area-select").value="All";$("#roadtrip-toggle").checked=false;$$('[data-day]').forEach(b=>b.classList.toggle("active",b.dataset.day==="All"));$$('[data-quick]').forEach(b=>b.classList.remove("active"));render()}
function bindControls(){$$("[data-day]").forEach(b=>b.onclick=()=>{state.day=b.dataset.day;$$('[data-day]').forEach(x=>x.classList.toggle("active",x===b));render()});$$("[data-quick]").forEach(b=>b.onclick=()=>{state.quick.has(b.dataset.quick)?state.quick.delete(b.dataset.quick):state.quick.add(b.dataset.quick);b.classList.toggle("active");render()});$("#search-input").oninput=e=>{state.query=e.target.value.trim();render()};$("#category-select").onchange=e=>{state.category=e.target.value;render()};$("#area-select").onchange=e=>{state.area=e.target.value;render()};$("#sort-select").onchange=e=>{state.sort=e.target.value;render()};$("#roadtrip-toggle").onchange=e=>{state.roadTrip=e.target.checked;render()};$("#clear-filters").onclick=reset;$("#empty-state button").onclick=reset;$("#open-plan").onclick=openDrawer;$(".close-drawer").onclick=closeDrawer;$("#drawer-scrim").onclick=closeDrawer;$("#open-favorites").onclick=()=>{reset();state.query="";const ids=[...state.favorites];$("#event-grid").innerHTML=ids.map(eventById).filter(Boolean).map(eventCard).join("");$("#result-summary").textContent=`${ids.length} saved event${ids.length===1?"":"s"}`;bindDynamic();document.querySelector("#events").scrollIntoView()};$("#surprise-button").onclick=()=>{const pool=filtered();if(pool.length)openDetail(pool[Math.floor(Math.random()*pool.length)].id)};$("#refresh-button").onclick=()=>toast(`Updated ${state.weekend.verifiedAt} · next scheduled research Wednesday 9 AM ET`);$("#copy-plan").onclick=async()=>{const lines=[...state.plan].map(eventById).filter(Boolean).sort((a,b)=>dateTime(a)-dateTime(b)).map(e=>`${e.day} ${e.time} — ${e.title} (${e.venue})\n${e.sourceUrl}`);if(!lines.length)return toast("Add something to your plan first");await navigator.clipboard.writeText(`Cincinnati This Weekend · ${state.weekend.shortLabel}\n\n${lines.join("\n\n")}`);toast("Itinerary copied")};$("#clear-plan").onclick=()=>{state.plan.clear();persist();render()};}
let deferredInstall;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;$("#install-button").hidden=false});$("#install-button").onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$("#install-button").hidden=true}};
async function init(){try{const response=await fetch("./data/current-weekend.json",{cache:"no-store"});if(!response.ok)throw new Error(`Data request ${response.status}`);const data=await response.json();state.events=data.events;state.weekend=data.weekend;updateEdition();populateSelects();$("#featured-rail").innerHTML=state.events.filter(e=>e.featured).slice(0,10).map(featureCard).join("");bindControls();bindDynamic();render();if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});}catch(error){$("#event-grid").innerHTML=`<div class="empty-state"><b>The verified edition could not load.</b><span>${esc(error.message)}. Please refresh once.</span></div>`;console.error(error)}}init();
